### ISSUE TITLE
Timeout for chat spammers

### ISSUE THREAD

**Issue by blinnlambert** [JasonZigelbaum/jqbx-issues#1]
We've been hit with trolls already! 

1. Make a timeout if someone clicks the "be a dj/step down" button too much. Our chat got flooded this morning by some troll who clicked it for a full minute. 

2. Chat timeout if someone is posting too frequently to chat. Same troll copy/pasted a smiley face a hundred times to flood the chat.

**Comment by JasonZigelbaum** [comment]
I think mod features fix this issue (you can just kick / ban a troll). Let me know if you feel otherwise. Closing for now.
