### ISSUE TITLE
[ISSUE] Spotify Connect toggles to different devices on song change

### ISSUE THREAD

**Issue by joshshowalter** [JasonZigelbaum/jqbx-issues#100]
There is a sporadic behavior where Spotify selects my Echo Dot, which is a Spotify Connect device, on song change when using JQBX. It happens seemly randomly, and the only way to fix this is to close the  JQBX.fm and quit Spotify and re-open both.

**Comment by JasonZigelbaum** [comment]
Hi Josh- can you try clicking the 'device' icon (on the top right, should
look like a laptop or a mobile phone) and selecting your preferred device
from the dropdown. Once you select the device you want to hear audio from
it should stick. Let me know if that works.

Thanks
