### ISSUE TITLE
[ISSUE] Javascript exceptions on Mac desktop app

### ISSUE THREAD

**Issue by wdrach** [JasonZigelbaum/jqbx-issues#102]
I can reliably reproduce Javascript exceptions when using the Mac electron app, seen below:

![screen shot 2018-03-07 at 2 20 00 pm](https://user-images.githubusercontent.com/2266534/37118889-ea226088-2212-11e8-9691-1c855b22241c.png)

I've found this happen reliably when clicking any of the queue management buttons (Empty, Shuffle, Sync) multiple times. I can reproduce by opening JQBX, loading a room, and clicking shuffle twice.

**Comment by JasonZigelbaum** [comment]
Thanks for bringing this to my attention. I can't replicate it which makes me thing it has something to do w/ one of the tracks on your queue. Do you mind sending me your spotify uri ( you'll probably want to send it in an email: jason[at]thebestagency.com ) so I can have a look at your queue and see if I can replicate it that way?

**Comment by wdrach** [comment]
Sent. Also just went to try and reproduce it, and noticed that the specific chain of events:

- Empty
- Add playlist to queue
- Shuffle


Reliably reproduces it more than shuffle --> shuffle again does. After that chain of events I get to a terminal state where I get an error on any of the queue management buttons.

**Comment by JasonZigelbaum** [comment]
Thanks- I was able to reproduce it after following those steps. I pushed a fix that should resolve the issue. The patched version is 0.9.142.
