### ISSUE TITLE
[Suggestion] Every track you play as DJ is automatically removed from queue, and empty queue automatically steps you down.

### ISSUE THREAD

**Issue by Thijmn** [JasonZigelbaum/jqbx-issues#106]
This to prevent AFK DJ's playing the same thing over and over again.

**Comment by intopuddles** [comment]
Wouldn't this just make them queue up huge playlists?

**Comment by Thijmn** [comment]
Many times, a person steps up as DJ, queues 1 or 2 songs and goes AFK. 
In a room where there is only a few DJs, this means that every few songs the same song is repeated over and over.

**Comment by dandanx** [comment]
There is an option in the Settings doing exactly this, the problem is, not everyone has enabled it.

**Comment by JasonZigelbaum** [comment]
Correct- there is a setting for this. Deselect "Keep tracks on my queue after they are played". I will consider switching this to the default but for now I just recommend enabling it if you would prefer that functionality.
