### ISSUE TITLE
Avatars are incorrect

### ISSUE THREAD

**Issue by colinswilliams** [JasonZigelbaum/jqbx-issues#11]
In the desktop app at least, I'm seeing avatars that are either blank, or repeated across different users (not done by the users themselves).

Screenshot attached.
![screen shot 2017-04-21 at 2 09 47 pm](https://cloud.githubusercontent.com/assets/1713954/25296305/7d7a9b20-269c-11e7-91a1-ace1ee54ace9.png)

**Comment by JasonZigelbaum** [comment]
Thanks for pointing this out. It was an issue with the URL encoding of saved images. Should be resolved now.
