### ISSUE TITLE
Sometimes skip place in que

### ISSUE THREAD

**Issue by roomx** [JasonZigelbaum/jqbx-issues#112]
After installing version Versjon 0.9.145 (0.9.145), sometimes the track will skip back at last line in cue just when it is about to play... Happened about 10 times in the last 10 days...

**Comment by JasonZigelbaum** [comment]
Hey that sounds annoying- sorry you're experiencing this issue! How many
hours a day would you say you are DJing? I'm trying to get an idea of how
often it happens per hour.

In any case will look into it further. Thanks for bringing it to my
attention.
