### ISSUE TITLE
Regression - Stop switching my Spotify audio-out

### ISSUE THREAD

**Issue by clounie** [JasonZigelbaum/jqbx-issues#119]
I like to control JQBX/Spotify from my desktop, but the audio is actually played from my laptop connected to speakers.

What I used to do is:
1) Start playing spotify music on my laptop
2) Start JQBX on my desktop

This would give me the above^

Now, every time a new song starts in JQBX, it switches my audio to my desktop. Basically unusable.

If I *wanted* the audio on my desktop, I'd switch it myself. Please stop JQBX from telling me where to play my music.

**Comment by JasonZigelbaum** [comment]
Are you using the web app? If you are can you try setting your audio output device within JQBX? You can do this by clicking the 'devices' link on the top right and selecting Spotify on your laptop, something like this screenshot: https://imgur.com/a/Qc08wUV

This way JQBX will know what device you are connected to and wont switch back after each play. Let me know if that fixes the issue. If not then I must be missing something.

Thanks,

**Comment by clounie** [comment]
An electron app for Linux based on the web app..but essentially yes.

That worked, thanks Jason!
