### ISSUE TITLE
Adding a song currently playing to your queue

### ISSUE THREAD

**Issue by colinswilliams** [JasonZigelbaum/jqbx-issues#12]
Upon clicking the plus icon, the song currently playing is added to your queue. My expectations would be that it would add to the bottom of your queue, so there isn't the risk of someone not paying attention of that song getting replayed so fast.

**Comment by plondon** [comment]
Hey @colinswilliams! You can change this in your profile settings. Just deselect "Add new tracks to the top of my queue"

<img width="438" alt="screen shot 2017-08-21 at 7 54 25 am" src="https://user-images.githubusercontent.com/5640772/29518086-0b5351e0-8646-11e7-8979-c49b1220b986.png">
