### ISSUE TITLE
Easy way to stop jqbx remotely

### ISSUE THREAD

**Issue by lazopm** [JasonZigelbaum/jqbx-issues#13]
Yesterday when I left work I locked my macbook but didn't close the app.
On the commute to work the app kept changing my music and there was no way to stop it.
I even tried using the web app to enter and leave a new room but it still kept controlling my music.

**Comment by AMerkuri** [comment]
Yeah, I have experienced same issue multiple times. Also for some reason when I left room my song progress bar was stuck in Spotify.
