### ISSUE TITLE
Allow more songs in the queue

### ISSUE THREAD

**Issue by Yaouza** [JasonZigelbaum/jqbx-issues#148]
Hi !

I would find it great if the queue could get bigger than 200 songs, 500 would be great !
Right now if I want to randomly play songs out of bg playlists it is quite a pain in the *** ;)

Thanks in advance for your consideration !

**Comment by KasanMoor** [comment]
Ya the first thing I did when I found this app was pull together a mega playlist for a new room only to be dissapointed it would only shuffle artists A - G

**Comment by Yaouza** [comment]
Queue size seem to have been increase, thanks a lot Jason !
