### ISSUE TITLE
Unable to login to Spotify thru Facebook on Mac App

### ISSUE THREAD

**Issue by DejayJD** [JasonZigelbaum/jqbx-issues#172]
Upon attempting to login to Spotify through Facebook to enable JQBX, I get the following error:

<img width="451" alt="Screen Shot 2019-05-08 at 2 06 38 PM" src="https://user-images.githubusercontent.com/6711655/57401099-8d3d0700-719a-11e9-808c-dac194ba6cb9.png">

**Comment by JasonZigelbaum** [comment]
I just checked this out on my local version and it worked- i'm thinking it
could be a loading issue or some sort of unexpected response (one time
only) can you check it again and let me know if you're still having issues?
Thanks.

**Comment by DejayJD** [comment]
I kept trying and eventually it let me in.
Not quite sure how to reproduce it again, but what was happening was I was clicking login with FB, getting that message, but the browser window would show my Spotify account page logged in (I could click around my account settings and whatnot).
I think logging in/out of spotify might have fixed it but I'm not sure since I cant get it to show up again.

I'll keep an eye out for it if it shows up again and maybe I can give some better insight.

Attached is a picture of my debugging process
![255iuxdit0g21](https://user-images.githubusercontent.com/6711655/57406593-b95e8500-71a6-11e9-9e90-31cbd5c9f6fb.jpg)

**Comment by DejayJD** [comment]
Closing as I'm not able to reproduce, will reopen if it shows up again
