### ISSUE TITLE
Scrolling on "My Account" only works when hovering over middle of page.

### ISSUE THREAD

**Issue by lzzzzzzzzzzzz** [JasonZigelbaum/jqbx-issues#177]
This is on desktop. When I load up the "My Account" page, scrolling up or down does not work if my mouse is not hovering over the centered page elements. 

![image](https://user-images.githubusercontent.com/49280887/59624845-dcfddf00-9105-11e9-9d88-b005b96f869d.png)

If I'm not on the middle portion of the page, where all my settings are, and the mouse is on the left or right side, scrolling with my scroll wheel doesn't work at all. 

However, clicking and holding the scroll wheel, then moving my mouse to scroll works.

**Comment by JasonZigelbaum** [comment]
Thanks for the info. Can you let me know what browser you are using and
what OS (windows, mac, linux)?

**Comment by lzzzzzzzzzzzz** [comment]
Hey Jason,

This is on my Windows 10 machine - I'm using Firefox version 67.0.1 (64-bit)

Fwiw it looks like a restart will update Firefox to the latest version. Let
me know if you want me to give that a go and retry.

**Comment by JasonZigelbaum** [comment]
Thanks for the info. I just checked it out on firefox and I had the same
issue. I looked into it and pushed a fix just now. It should be working
now, let me know if you're still having problems.

Thanks again!

**Comment by lzzzzzzzzzzzz** [comment]
Apparently I never checked your last message! But yes we definitely know this works now. :) closing issue.
