### ISSUE TITLE
[ISSUES][Web App] JQBX plays the last track listened to on Spotify

### ISSUE THREAD

**Issue by MetalHeel** [JasonZigelbaum/jqbx-issues#188]
Recently the JQBX web app has had trouble playing the tracks chosen in the web app. Very frequently it'll play whatever I last listened to on standard Spotify - or will stop playing entirely. If I hit "Sync Audio" a bunch of times, I can eventually get it back on track, but this happens every day now.

Some info:
- Chrome browser
- Windows 10
- Spotify via desktop
- A lot of Spotify iOS app usage

**Comment by JasonZigelbaum** [comment]
Thanks for logging this. This looks like it's an issue on Spotify's end
though. Their streaming api is playing the last song for one reason or
another at more or less random times. I'll keep the ticket open in case it
doesn't fix itself over the next couple of days. I'll file a ticket w/
Spotify also and see what they have to say.

**Comment by DMCK96** [comment]
Any update from Spotify on this? It's happening pretty consistently on near enough every song both myself and others in our office try playing, we've had to stop using JQBX for the time being till it fixes itself as it's requiring us to sync audio every 3-4 minutes.

**Comment by JasonZigelbaum** [comment]
There are a couple of tickets open on their issue tracker github. See:
https://github.com/spotify/web-playback-sdk/issues/101.

Not much more I can do except hope they sort their stuff out. In the
meanwhile this should be a workaround:

1. Open the Spotify app on your computer
2. Click the Devices icon on the top right (next to your user image)
3. Select the Spotify App on your computer
4. Now audio should be playing directly from your Spotify app and not the
web player.
5. Audio coming out of your Spotify app does not seem to be effected by
this bug.

Let me know if that helps / any other questions. Sorry about the
inconvenience- wish I could do something about it. Also if that doesn't
work you can try clearing your Spotify queue on your Spotify app - it seems
that having a pre-existing queue is part of the issue.

**Comment by MetalHeel** [comment]
I'm finding that on transition to a new track, the output will keep switching back over to the "JQBX Web Player" when I try to choose Spotify as my device. For my usage, I'm okay with having to sync from time to time, though it'll be nice when Spotify gets this resolved.

It does seem like the mobile app isn't experiencing this though, which is strange. Is it not using the same API?

**Comment by humusdigital** [comment]
Some one have updates about this issue, I develop an app with Web Playback SDK and I needed to turn off this because this issue. Some one know how fix this issue to continue using the Web Playback SDK. At the moment in the web player is playing only one track over my custom device. thans a lot

**Comment by JasonZigelbaum** [comment]
No it's not the same API - the mobile apps function differently.

Also you will want to click the devices icon *within JQBX* not from within
Spotify. You have to tell JQBX where to point the audio or else it will
just reset after each new track.

**Comment by MetalHeel** [comment]
Choosing Spotify as my device to be used with JQBX does appear to be a workaround for this. I'm not seeing any syncing issues with this route.

**Comment by JasonZigelbaum** [comment]
Thanks - if you can spread the word that would be helpful. I will do the
same.

**Comment by DMCK96** [comment]
Unfortunately for those of us casting to Chromecast devices via the Chrome browser this workaround doesn't resolve the issue. If there are any workarounds that allow the audio to remain within the browser window as opposed to coming from the Spotify application, then it'd be great if we could have them outlined in this issue when they're found.

Cheers.

**Comment by JasonZigelbaum** [comment]
Hi Daniel,

Ah I see. The good news is that the bug should be fixed according to
Spotify's response here:

https://github.com/spotify/web-playback-sdk/issues/101

Can you try it out and let me know if things are working properly on your
end?

Thanks,

**Comment by MetalHeel** [comment]
For me at least, as of this morning I'm no longer having this issue going purely through the web browser.

**Comment by MetalHeel** [comment]
I have not experienced this issue in a week. Going ahead and closing.
