### ISSUE TITLE
Export Room button gone? 

### ISSUE THREAD

**Issue by fma965** [JasonZigelbaum/jqbx-issues#190]
![image](https://user-images.githubusercontent.com/1707290/74191588-cb94b480-4c4b-11ea-8f48-bc056bf9fe7e.png)
https://www.jqbx.fm/faq has references to this place

**Comment by JasonZigelbaum** [comment]
Sorry I need to update the docs for that. The function still exists but now
you can export the track history of a room by clicking the "history" tab
and then click "Export to Playlist". Thanks for pointing tha tout.

**Comment by fma965** [comment]
Thanks. i will keep this in mind :)

**Comment by fma965** [comment]
Is there a 100 song max i assume?

**Comment by JasonZigelbaum** [comment]
Yes correct - it just exports the last 100 songs played in that room (this
was always the case since that's all we keep track of).
