### ISSUE TITLE
Rework/Disable down-vote button

### ISSUE THREAD

**Issue by TurtleTony** [JasonZigelbaum/jqbx-issues#199]
Me and a bunch of people in the [any-every](https://app.jqbx.fm/room/any-every) room would love to be able to disable the nope feature for the room.
The current implementation does not feel like a user is just saying "Meh, I don't like this song" but with the big read thumbs down and vote gauge it really feels like "BOOOH GET OFF THE STAGE AND SKIP THIS SONG IMMEDIATELY".
It makes dj's feel anxious whether or not to skip the song and might scare other people off from playing 'off-topic' or 'unusual' songs in the first place.
That however is the idea of the room, playing anything and everything.
So a room setting to disable down-voting in general or a different graphical implementation of the voting system would be the requested feature.

**Comment by gilluminate** [comment]
Would love to see a Neutral button which allows for a vote even if you aren't super stoked about a song but don't hate it either.

**Comment by Ghoelian** [comment]
I don't feel like this is the case at all, the bar only becomes red if the majority of the votes are nopes. We in Sea of Metal just tell new users upfront that we do allow downvoting, and that it's nothing personal. So far we have not had any issues with people getting anxious from the nopes.

Also @gilluminate there is a neutral option, don't vote.

**Comment by LeipSnoepje** [comment]
@TurtleTony is requesting a function to disable the button in the room settings. Not requesting to delete the button in general. In rooms where downvotes aren't allowed this can be pretty useful.

**Comment by gilluminate** [comment]
@Ghoelian but that could also mean the user isn't even paying attention. I'm here, I'm listening, I'm participating, but I am ambivalent.

**Comment by Ghoelian** [comment]
> @Ghoelian but that could also mean the user isn't even paying attention. I'm here, I'm listening, I'm participating, but I am ambivalent.

@gilluminate That is true, hadn't thought about that. Regardless, I feel a button like that wouldn't really add anything to the user experience.

**Comment by raymondruesink** [comment]
Being able to disable the nope-button in the room settings would be a very nice feature
