### ISSUE TITLE
Feature Request: remove song from playlist after it plays

### ISSUE THREAD

**Issue by mattbowes** [JasonZigelbaum/jqbx-issues#202]
It would be nice if there was an option to automatically remove songs from the playlist after they play.

**Comment by JasonZigelbaum** [comment]
You can do this by clicking Settings -> Queue Settings -> Remove the box
that reads "Keep tracks on my queue after they get played"

**Comment by mattbowes** [comment]
Thanks for pointing that out, will close the issue
