### ISSUE TITLE
Proper Fullscreen on macOS

### ISSUE THREAD

**Issue by copey02** [JasonZigelbaum/jqbx-issues#21]
Clicking the full-screen button on the mac app right now just maximizes the screen, instead of going into a proper full-screen macOS desktop space. 

Depending on my workspace (ie laptop, no external monitors), I heavily use native macOS full-screen apps to keep window clutter to a minimum, making it easy to switch between applications.

**Comment by copey02** [comment]
just noticed that using the View menu > "Toggle Full Screen" option does do the proper full-screen mode. Clicking the green maximize button does not work as expected (default macOS behavior). 
At least the option is there though to accomplish what I am looking for

**Comment by JasonZigelbaum** [comment]
Thanks for letting me know. I changed the behavior of the fullscreen button to do what you expect.
