### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by gilluminate** [JasonZigelbaum/jqbx-issues#215]
Any plans to open source the code here in github so we can collaborate with you on adding features? I'd love to get involved and help out with the project.

**Comment by jorepstein** [comment]
A ton of people would appreciate this. I know a lot of developers on jqbx who'd like to contribute.
I know that back in September Jason mentioned open sourcing the browser front end but maybe not doing so for the backend or mobile.

**Comment by Spark3000** [comment]
PLUS ONE :)

**Comment by JasonZigelbaum** [comment]
The plans to open it up are weird because of a few of things that I can't
get into unfortunately. But a small group is working on Open sourcing bots
so that's at least a step in the right direction. Will follow up here when
that repo is public.
