### ISSUE TITLE
Can't get back into the Room I created.

### ISSUE THREAD

**Issue by bacchustiger** [JasonZigelbaum/jqbx-issues#25]
I'm new to JQBX and created a room last night called "Unicorn Tears". Now, when I log into JQBX, I can see the room under "My Rooms", but when I click on it, I get this error: "This page no longer exists".

 I believe that the uri I added for it was unicorntears. 

Thanks,
  
Tony

**Comment by JasonZigelbaum** [comment]
Sorry about that! There was an issue when deciding whether to look the room up by id or by handle. This should be resolved and you should be able to access your room now.

Let me know if you're still having the issue & thanks for letting me know!
