### ISSUE TITLE
@User mentions [Feature]

### ISSUE THREAD

**Issue by ebabel** [JasonZigelbaum/jqbx-issues#29]
1. Receive a bing/notification when someone mentions your username like @UserName. 

2. When typing "@" pop-up with users in room and offer auto-complete.

**Comment by DonPage** [comment]
+1, but I would also add the option of turning the "bing" off.

**Comment by jtrutwin-zz** [comment]
+1, but I think something on dashboard like unread mentions count would be nice in addition to audio bing so you know to scroll the chat.  IDK can get complicated quickly.
