### ISSUE TITLE
Empty Queue Button

### ISSUE THREAD

**Issue by DrizzyWay** [JasonZigelbaum/jqbx-issues#31]
Is it possible to get an "are you sure" prompt for the empty queue button? I totally just accidentally hit it.

**Comment by JasonZigelbaum** [comment]
Sorry! I added a "are you sure" dialog to the actions on the desktop and web apps. Going to close this out- let me know if for some reason it's not working for you.

Thanks!

**Comment by DrizzyWay** [comment]
Thanks man. just tried it out and it looks good.
