### ISSUE TITLE
No way to reset state of Dope/Lame

### ISSUE THREAD

**Issue by lazopm** [JasonZigelbaum/jqbx-issues#4]
Clicking active Dope or Lame buttons should toggle the state back to neither option selected.

**Comment by jtrutwin-zz** [comment]
+1 you should be allowed one vote reset I think.  Don't wanna allow constant troll toggling.

**Comment by clounie** [comment]
One reset to neutral + one change of vote allowed?

Where
Reset to neutral = pressing the currently selected vote button
Change of vote = pressing the button not currently selected
