### ISSUE TITLE
Auto Dope?

### ISSUE THREAD

**Issue by jtrutwin-zz** [JasonZigelbaum/jqbx-issues#6]
I usually listen while working so I try to upvote when I can, wouldn't mind an option to Auto Up-vote.

Just a thought, fine to ignore....

**Comment by copey02** [comment]
would also like this. or at least a keyboard shortcut to Like/Dislike so can easily switch windows, vote and go back to business.

**Comment by thephenakist** [comment]
This doesn't seem like a helpful feature. Doping is a user interaction and shouldn't be left to automation. That's like asking for a computer to lift your arm up and turn on your lighter at a concert because you're too busy looking at your phone. -1 for me

**Comment by jtrutwin-zz** [comment]
Snarky comments aside, just gonna close this - there are easy jquery bookmarklets that accomplish it anyway.
