### ISSUE TITLE
Separate gifs for Dope/Lame/Novote

### ISSUE THREAD

**Issue by jtrutwin-zz** [JasonZigelbaum/jqbx-issues#7]
Would be kinda cool to be able to customize your profile pic/gif depending on your vote.

Maybe one gif for Dope/Upvote (showing head bobbing TT gif for example)
Another one for Lame, another one for if not vote cast.

**Comment by JasonZigelbaum** [comment]
Love that idea, thanks! Added it in (included a gif for djing as well). You can set them in your account page.
