### ISSUE TITLE
Saved Songs/Albums etc

### ISSUE THREAD

**Issue by clounie** [JasonZigelbaum/jqbx-issues#79]
Would be nice to be able to see my saved songs in JQBX, as that's where a large portion of new finds / songs I'd want to play for people reside.

**Comment by LorenzKahl** [comment]
+1

**Comment by JasonZigelbaum** [comment]
Do you mean songs in your Spotify library? If so you can get to it by clicking "Playlists" -> "Your Spotify Library" at the bottom. Let me know if that's not what you expect. Closing for now.

**Comment by clounie** [comment]
Could you put it up top instead of down at the bottom?

For two reasons:
1) Spotify's UI has it at the top, so it's weird for an application mirroring Spotify (to some extent) to do the exact opposite
2) For those of us with hundreds of playlists (and playlist folders, and nested folders), it really sucks to scroll all the way down to get there...every. single. time.
