### ISSUE TITLE
Spotify volume lowers gradually when in a JQBX room

### ISSUE THREAD

**Issue by jonzhan** [JasonZigelbaum/jqbx-issues#81]
macOS 10.13.2 / Spotify 1.0.70.388.g8e1ed5af / JQBX Version 0.9.132
(Haven't tested Windows)

I'm experiencing some curious behavior, in which the volume in Spotify gradually drops by -15% of max volume after entering a JQBX room. (For instance, if I start at 50% volume in Spotify, I end up at about 35%. If I start at 30%, it drops to 15%). This seems to occur whether or not the room has an active DJ.

My steps to reproduce:

1. Play music in Spotify, with JQBX not running for 60 sec. (no change in volume observed)
2. Start JQBX (no change in volume observed for 60 sec)
3. Enter a JQBX room (volume begins falling after 5-10 sec)

**Comment by JasonZigelbaum** [comment]
Thanks for the thorough report!

I was able to replicate it and found out it was due to a rounding error. I pushed a fix for it (ver 0.9.134). You should be prompted to update the next time you open the app. Let me know if anything else comes up.

**Comment by jonzhan** [comment]
Wow, fast patch! Thanks for the awesome app. 👍
