### ISSUE TITLE
[ISSUE] [ANDROID] Hitting Back Button closes app instead of minimizes

### ISSUE THREAD

**Issue by CaptInternet** [JasonZigelbaum/jqbx-issues#86]
for many applications hitting the back will just minimize an app instead of outright closing it. Could this be implemented for jqbx, or at least give a confirmation before closing?

**Comment by clounie** [comment]
+1, pretty much no apps exit on back.

**Comment by JasonZigelbaum** [comment]
Yes I'm an iOS user so I didn't know this was a thing. I'll look into it and try to push a fix this week. Thanks for letting me know!

**Comment by CaptInternet** [comment]
Sweet. Yeah, most of the users in my room (The Pop Punk one) are Android users, and they have all been throwin' fits, (including myself). it's been causing people to lose their spots and whatnot.

So I've been gathering up all the android issues. Let me know when to have people look for the update :)

**Comment by JasonZigelbaum** [comment]
I think this is resolved- let me know if you're still having issues, closing for now.

Thanks
