### ISSUE TITLE
[ISSUE] [ANDROID} Sliding function not working correctly in song queue

### ISSUE THREAD

**Issue by CaptInternet** [JasonZigelbaum/jqbx-issues#87]
Another large pain point:

When trying to swipe a song left to view queue controls, it either doesn't work at all, or you have to swipe multiple times to access the menu.

Also, dragging songs up or down is extremely unreliable. the item either gets stuck in midair or it is unpredictable where it will land in the queue.

**Comment by CaptInternet** [comment]
Any update on this issue in particular? It's almost impossible to manage queues on android the way things stand right now, incredibly frustrating and ends up slowing down the app itself to a crawl, especially if you're looking through your queue for something.

**Comment by JasonZigelbaum** [comment]
Working on it now. Roughly how many tracks do you have in your queue when you experience issues?

**Comment by CaptInternet** [comment]
I'm slightly worried, ever since the change, any songs I delete from my queue re-add right after the DJ changes. 

For Android as of now.

**Comment by JasonZigelbaum** [comment]
Annoying. So long story short the queue needs work to be optimized and functional on mobile. Will take a minute for me to fix it- will keep you posted on updates this week. In the meanwhile I posted a quick fix that should resolve the 'remove' issue as well as an issue where the top track plays more then once. If those issues persist after the latest update let me know. I will keep you in updated when I post a more comprehensive fix.

**Comment by CaptInternet** [comment]
This looks good now! :)
