### ISSUE TITLE
Refreshing queue [Feature]

### ISSUE THREAD

**Issue by lazopm** [JasonZigelbaum/jqbx-issues#9]
When I update my queue list on the Spotify app, the changes don't reflect in JQBX.
I use the back and then forward buttons to get the app to fetch the updated list.
Possible solutions:

1. Listen to change events on the playlist.  (don't know if it's possible with the Spotify API)
2. Refresh Button
3. Polling ?

**Comment by JasonZigelbaum** [comment]
If you click the 'sync' button it will make sure that the "JQBX :: Queue" playlist is in sync between Spotify and JQBX (in addition to syncing the Spotify audio with the room).

I'll look into making the UI more obvious though- maybe add a button within the Queue UI itself so it's more clear.
