### ISSUE TITLE
[ISSUE] [ALL?] Playlist Import Limit

### ISSUE THREAD

**Issue by CaptInternet** [JasonZigelbaum/jqbx-issues#91]
Was reported for iOS, but I believe it's affecting multiple builds. There seems to be a limit of how many songs will transfer from any playlist. This limit is 200. I'll try to do some testing with Android and Web later.

See below album for examples (thanks to slickdtc):
https://imgur.com/gallery/K0Nbh

**Comment by JasonZigelbaum** [comment]
Correct- there is a limit of 200 tracks that can be added in bulk to the queue. This was done in an effort to keep lists within a reasonable size. I'll consider raising the limit but for now it needs to stay until rendering is better optimized.
