### ISSUE TITLE
[ISSUE] [ALL] JQBX handles can be spoofed

### ISSUE THREAD

**Issue by CaptInternet** [JasonZigelbaum/jqbx-issues#96]
As it stands currently, I can use someone exact's username, and chat can't tell a difference. it actually thinks you're speaking AS that person, so it doesn't create a new conversation thread or anything.

This could end up being a bigger problem later on down the line, and could be abused easily.

**Comment by JasonZigelbaum** [comment]
True- they usernames can be duplicated. This is a feature though since it's all meant to be good fun :)

Duped usernames shouldn't continue the same thread though- I've pushed a fix for that on the website. Will roll it out to mobile and MacOS shortly.
